// Compiles HLSL to DXBC with the d3dcompiler_47 of the Wine it runs under and writes the bytes as a C array.
// Used by tools/gen-dxbc-test-shaders.sh to make tests/shaders/dxbc_*.h; not part of the test run.
//   dxbc_compile.exe <input.hlsl> <entry> <target, e.g. vs_5_0> <output.h> <array name>
#include <windows.h>
#include <unknwn.h>

#include <cstdio>
#include <vector>

struct Blob : IUnknown {
    virtual LPVOID STDMETHODCALLTYPE GetBufferPointer() = 0;
    virtual SIZE_T STDMETHODCALLTYPE GetBufferSize() = 0;
};

using CompileFn = HRESULT(WINAPI *)(LPCVOID, SIZE_T, LPCSTR, const void *, void *, LPCSTR, LPCSTR, UINT, UINT, Blob **, Blob **);

int main(int argc, char **argv)
{
    if (argc != 6) {
        std::fprintf(stderr, "usage: dxbc_compile <input.hlsl> <entry> <target> <output.h> <name>\n");
        return 2;
    }
    FILE *in = std::fopen(argv[1], "rb");
    if (!in) {
        std::fprintf(stderr, "cannot read %s\n", argv[1]);
        return 1;
    }
    std::vector<char> source;
    char chunk[4096];
    for (size_t n; (n = std::fread(chunk, 1, sizeof(chunk), in)) > 0;)
        source.insert(source.end(), chunk, chunk + n);
    std::fclose(in);

    HMODULE compiler = LoadLibraryA("d3dcompiler_47.dll");
    auto compile = compiler ? reinterpret_cast<CompileFn>(reinterpret_cast<void *>(GetProcAddress(compiler, "D3DCompile"))) : nullptr;
    if (!compile) {
        std::fprintf(stderr, "d3dcompiler_47.dll has no D3DCompile\n");
        return 1;
    }
    Blob *code = nullptr, *errors = nullptr;
    const HRESULT hr = compile(source.data(), source.size(), argv[1], nullptr, nullptr, argv[2], argv[3], 0, 0, &code, &errors);
    if (errors)
        std::fprintf(stderr, "%s\n", static_cast<const char *>(errors->GetBufferPointer()));
    if (FAILED(hr) || !code) {
        std::fprintf(stderr, "D3DCompile failed: 0x%08lx\n", static_cast<unsigned long>(hr));
        return 1;
    }
    FILE *out = std::fopen(argv[4], "wb");
    if (!out)
        return 1;
    const unsigned char *bytes = static_cast<const unsigned char *>(code->GetBufferPointer());
    std::fprintf(out, "// Generated by tools/gen-dxbc-test-shaders.sh from tests/shaders/dxbc.hlsl (%s, %s). Do not edit.\n", argv[2], argv[3]);
    std::fprintf(out, "static const unsigned char %s[] = {", argv[5]);
    for (SIZE_T i = 0; i < code->GetBufferSize(); ++i)
        std::fprintf(out, "%s0x%02x,", i % 16 ? " " : "\n    ", bytes[i]);
    std::fprintf(out, "\n};\n");
    std::fclose(out);
    return 0;
}
