d3d12_sources += files(
  '../common/blob.cpp',
  '../common/platform.cpp',
  '../common/private_data.cpp',
  'clear_value.cpp',
  'command_list.cpp',
  'command_queue.cpp',
  'descriptor_heap.cpp',
  'descriptors.cpp',
  'dred.cpp',
  'device.cpp',
  'exports.cpp',
  'fence.cpp',
  'formats.cpp',
  'heap.cpp',
  'pipeline_state.cpp',
  'pipeline_stream.cpp',
  'resource.cpp',
  'root_signature.cpp',
  'root_signature_blob.cpp',
  'root_signature_deserializer.cpp',
  'root_signature_exports.cpp',
)
