#!/usr/bin/env python3
"""Generates the Wine unix-call transport of the mtlb bridge from mtlb.h.

mtlb.h is the single description of the bridge API. Every `MTLB_EXPORT`
prototype in it becomes one unix call:

  <out>/mtlb_wine_params.h   function indices and one parameter struct per
                             function (the arguments, then the result); shared
                             by both sides of the transport
  <out>/mtlb_wine_client.inc PE side: definitions of the mtlb_* functions that
                             pack their arguments and call the dispatcher
  <out>/mtlb_wine_unix.inc   unix side: one entry per function unpacking the
                             parameters and calling the real implementation,
                             plus the __wine_unix_call_funcs table

Pointers are passed as they are: the PE and unix sides of a Wine process share
one address space. A `const char *` result is copied into the parameter struct.
"""
import os
import re
import sys

STRING_RESULT_SIZE = 512
# Functions the logging itself uses: tracing them would recurse.
NO_TRACE = {"mtlb_log_write", "mtlb_configure"}
KNOWN_RESULTS = {
    "mtlb_result": "MTLB_ERROR_DEVICE",  # what a failed transport reports
    "uint64_t": "0",
    "void": None,
    "const char *": '""',
}


def parse(header):
    text = open(header).read()
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//[^\n]*", "", text)
    functions = []
    for m in re.finditer(r"\bMTLB_EXPORT\s+([^;(]*?)\b(mtlb_\w+)\s*\(([^)]*)\)\s*;", text):
        ret = re.sub(r"\s+", " ", m.group(1)).strip()
        ret = re.sub(r"\s*\*\s*$", " *", ret)
        name = m.group(2)
        params = []
        arg_text = m.group(3).strip()
        if arg_text and arg_text != "void":
            for arg in arg_text.split(","):
                am = re.match(r"^(.*?)(\w+)$", arg.strip())
                params.append((am.group(1).strip(), am.group(2)))
        if ret not in KNOWN_RESULTS:
            sys.exit(f"{name}: unsupported result type '{ret}'")
        functions.append((ret, name, params))
    if not functions:
        sys.exit("no MTLB_EXPORT functions found in " + header)
    return functions


def ctype(type_, name):
    """`type name`, with no space after a trailing '*'."""
    return f"{type_}{name}" if type_.endswith("*") else f"{type_} {name}"


def decl(type_, name):
    return ctype(type_, name) + ";"


def params_header(functions):
    out = ["/* Generated by tools/gen_mtlb_wine.py from mtlb.h. Do not edit. */",
           "#ifndef MTLB_WINE_PARAMS_H", "#define MTLB_WINE_PARAMS_H", "",
           '#include "bridge/mtlb.h"', "", "enum mtlb_wine_func {"]
    out += [f"    MTLB_WINE_{name}," for _, name, _ in functions]
    out += ["    MTLB_WINE_FUNC_COUNT", "};", ""]
    out += ["static const char *const mtlb_wine_func_names[] = {"]
    out += [f'    "{name}",' for _, name, _ in functions]
    out += ["};", ""]
    for ret, name, params in functions:
        out.append(f"struct mtlb_wine_{name}_params {{")
        fields = [decl(t, n) for t, n in params]
        if ret == "const char *":
            fields.append(f"char ret[{STRING_RESULT_SIZE}];")
        elif ret != "void":
            fields.append(decl(ret, "ret"))
        if not fields:
            fields.append("uint64_t reserved;")
        out += [f"    {f}" for f in fields]
        out += ["};", ""]
    out.append("#endif")
    return "\n".join(out) + "\n"


def arg_values(params):
    return ", ".join(f"(uint64_t)(uintptr_t)({n})" for _, n in params)


def trace_before(name, params, prefix=""):
    if name in NO_TRACE:
        return ""
    n = len(params)
    vals = arg_values([(t, prefix + nm) for t, nm in params])
    arr = f"uint64_t args_[] = {{{vals}}}; " if n else ""
    call = f"mtlb_wine_trace_call(MTLB_WINE_SIDE, \"{name}\", {'args_' if n else 'NULL'}, {n});"
    return f"    if (MTLB_WINE_LOG()) {{ {arr}{call} }}"


def client_inc(functions):
    out = ["/* Generated by tools/gen_mtlb_wine.py from mtlb.h. Do not edit. */", ""]
    for ret, name, params in functions:
        sig = ", ".join(ctype(t, n) for t, n in params) or "void"
        out.append(ctype(ret, f"{name}({sig})"))
        out.append("{")
        out.append(f"    struct mtlb_wine_{name}_params p;")
        out.append("    memset(&p, 0, sizeof(p));")
        out += [f"    p.{n} = {n};" for _, n in params]
        out.append(trace_before(name, params))
        fail = KNOWN_RESULTS[ret]
        failure = "return;" if fail is None else f"return {fail};"
        out.append(f"    if (!mtlb_wine_call(MTLB_WINE_{name}, &p, \"{name}\")) {failure}")
        if ret == "const char *":
            out.append("    static MTLB_THREAD_LOCAL char text_[%d];" % STRING_RESULT_SIZE)
            out.append("    memcpy(text_, p.ret, sizeof(text_));")
            out.append("    return text_;")
        elif ret == "void":
            out.append('    if (MTLB_WINE_LOG()) mtlb_wine_trace_result(MTLB_WINE_SIDE, "%s", 0, 0);' % name)
        else:
            out.append('    if (MTLB_WINE_LOG()) mtlb_wine_trace_result(MTLB_WINE_SIDE, "%s", (int64_t)p.ret, 1);' % name)
            out.append("    return p.ret;")
        out += ["}", ""]
    return "\n".join(out)


def unix_inc(functions):
    out = ["/* Generated by tools/gen_mtlb_wine.py from mtlb.h. Do not edit. */", ""]
    for ret, name, params in functions:
        out.append(f"static int32_t unix_{name}(void *args)")
        out.append("{")
        out.append(f"    struct mtlb_wine_{name}_params *p = (struct mtlb_wine_{name}_params *)args;")
        out.append(trace_before(name, params, "p->"))
        out.append("    MTLB_UNIX_POOL_BEGIN")
        call_args = ", ".join(f"p->{n}" for _, n in params)
        if ret == "void":
            out.append(f"    {name}({call_args});")
        elif ret == "const char *":
            out.append(f"    strncpy(p->ret, {name}({call_args}), sizeof(p->ret) - 1);")
        else:
            out.append(f"    p->ret = {name}({call_args});")
        out.append("    MTLB_UNIX_POOL_END")
        if ret in ("void", "const char *"):
            out.append('    if (MTLB_WINE_LOG()) mtlb_wine_trace_result(MTLB_WINE_SIDE, "%s", 0, 0);' % name)
        else:
            out.append('    if (MTLB_WINE_LOG()) mtlb_wine_trace_result(MTLB_WINE_SIDE, "%s", (int64_t)p->ret, 1);' % name)
        out += ["    return 0;", "}", ""]
    out.append("MTLB_UNIX_TABLE_EXPORT extern const unixlib_entry_t __wine_unix_call_funcs[];")
    out.append("MTLB_UNIX_TABLE_EXPORT const unixlib_entry_t __wine_unix_call_funcs[] = {")
    out += [f"    unix_{name}," for _, name, _ in functions]
    out.append("};")
    out.append("")
    out.append("MTLB_STATIC_ASSERT(sizeof(__wine_unix_call_funcs) / sizeof(__wine_unix_call_funcs[0]) == MTLB_WINE_FUNC_COUNT, \"unix call table size\");")
    return "\n".join(out) + "\n"


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_mtlb_wine.py <mtlb.h> <output dir>")
    functions = parse(sys.argv[1])
    out_dir = sys.argv[2]
    os.makedirs(out_dir, exist_ok=True)
    for name, text in (("mtlb_wine_params.h", params_header(functions)),
                       ("mtlb_wine_client.inc", client_inc(functions)),
                       ("mtlb_wine_unix.inc", unix_inc(functions))):
        with open(os.path.join(out_dir, name), "w") as f:
            f.write(text)


if __name__ == "__main__":
    main()
